#%RAML 1.0 Library
uses:
  annotations: ../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  daysOfCashOutstanding:
    type: object
    description: "It measures the period in days that can be covered with the available cash, banks and temporary investments."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: false

      isCalculated:
        type: boolean
        description: |
          It is calculated, if the value is true, it is because the risk tool could calculate it, otherwise its value is false and likewise it ratifies when the value is a possible 0.
        required: true

