#%RAML 1.0 Library
uses:
  annotations: ../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  cashConversionCycle:
    type: object
    description: "It measures the time in days it takes for a company to convert its investments in inventory and other resources into cash flows from sales."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: false

      isCalculated:
        type: boolean
        description: |
          It is calculated, if the value is true, it is because the risk tool could calculate it, otherwise its value is false and likewise it ratifies when the value is a possible 0.
        required: true

