#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  financingExpensesToSales:
    type: object
    description: "This ratio comparises the financing expenses to the amount of sales of the period."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

