#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  debtToIncome:
    type: object
    description: "Is the percentage of the company´s gross monthly income that goes to paying its monthly debt payments."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

