#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  roa:
    type: object
    description: "The return on assets (ROA) shows the percentage of how profitable a company's assets are in generating revenue."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

