#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  assets:
    type: object
    description: "Asstes of change of scale of the sales."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

