#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  variationOnSales:
    type: object
    description: "Variation on sales between last year and current year."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

