#%RAML 1.0 Library
uses:
  annotations: ../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  balance: body.details.detailsElements.delegationInput.participants.financialStatements.accountingAccounts.balance.raml
  accountsCategory: body.details.detailsElements.delegationInput.participants.financialStatements.accountingAccounts.accountsCategory.raml

types:
  accountingAccounts:
    type: object
    description: "Accounting accounts of the financial statement."
    properties:
      id:
        type: string
        description: |
          Identifier of the account(code).
        required: true

      balance:
        type: balance.balance
        description: |
          Amount associated to the account (this type of data includes amount and currency).
        required: true

      accountsCategory:
        type: accountsCategory.accountsCategory
        description: |
          Information regarding the type of account, level, and group to which the financial statement belongs.
        required: true

    