#%RAML 1.0 Library
uses:
  annotations: ../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  proposal: body.details.detailsElements.delegationInput.proposal.raml
  participants: body.details.detailsElements.delegationInput.participants.raml
  attributions: body.details.detailsElements.delegationInput.attributions.raml

types:
  delegationInput:
    type: object
    discriminator: detailsType
    discriminatorValue: DELEGATION_INPUT
    description: "Input information for the delegation control module."
    properties:
      detailsType:
        type: string
        description: |
          Details or notice code.
        required: true
        enum: [DELEGATION_INPUT,DELEGATION_OUTPUT]
        (annotations.enumDescription):
        - DELEGATION_INPUT: "Input information for the delegation control module."
        - DELEGATION_OUTPUT: "Output information for the delegation control module."

      proposal:
        type: proposal.proposal
        description: |
          Information about the risk proposal which is going to be analyzed.
        required: true

      participants:
        type: participants.participants[]
        description: |
          It refers when the proposal information is evaluated and input from participant of the proposal.
        required: true

      attributions:
        type: attributions.attributions[]
        description: |
          Attribution information module.
        required: true

