#%RAML 1.0 Library
uses:
  annotations: ../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  totalIncomes:
    type: object
    description: "Total incomes from all employers"
    properties:
      amount:
        type: number
        description: |
          Monetary amount.
        required: true

      currency:
        type: string
        description: |
          String based on ISO-4217 for specifying the currency
        required: true

