#%RAML 1.0 Library
uses:
  annotations: ../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  identityDocument: data.person.identityDocument.raml

types:
  person:
    type: object
    description: "Person associated with calculation."
    properties:
      identityDocument:
        type: identityDocument.identityDocument
        description: |
          Identity document information.
        required: true

      firstName:
        type: string
        description: |
          First name of the Customer.
        required: true

        (annotations.customControlAttributes):
        - kind: AUDITABLE_DATA
          country: CO
      middleName:
        type: string
        description: |
          Middle name of the Customer .
        required: false

        (annotations.customControlAttributes):
        - kind: AUDITABLE_DATA
          country: CO
      lastName:
        type: string
        description: |
          Last name of the participant.
        required: true

        (annotations.customControlAttributes):
        - kind: AUDITABLE_DATA
          country: CO
