#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  daysOfCashOutstanding:
    type: object
    description: "It measures the period in days that can be covered with the available cash, banks and temporary investments."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

