#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  averagePaymentPeriod:
    type: object
    description: "This ratio measures the average number of days it takes a business to pay its vendors for purchases made on credit."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

