#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  behavioralDefaultProbability: data.details.detailsElements.participantInputModel.fastTrackEligibility.behavioralDefaultProbability.raml
  riskGroup: data.details.detailsElements.participantInputModel.fastTrackEligibility.riskGroup.raml

types:
  fastTrackEligibility:
    type: object
    description: "Participant segment or sector model asigned to perform risk evaluation due to participant economic."
    properties:
      behavioralDefaultProbability:
        type: behavioralDefaultProbability.behavioralDefaultProbability
        description: |
          Is a measure of credit evaluation that is given internally with the payments behavior of a customer in order to estimate its unfulfillment probability.
        required: true

      riskGroup:
        type: riskGroup.riskGroup
        description: |
          It is an indicator of the quality of the customer according to its probability of default. It varies from 1 to 99. The higher this number, the riskier the customer.
        required: true

