#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  acidTest:
    type: object
    description: "Ratio to measure the ability of a company to use its near cash or quick assets to extinguish or retire its current liabilities immediately."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

