#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  qualitativeVariables:
    type: object
    description: "Qualitative variables."
    properties:
      id:
        type: string
        description: |
          A unique key for each variable in the rating model.
        required: true

      value:
        type: string
        description: |
          Value of the variable qualitative.
        required: true

      variableType:
        type: string
        description: |
          Value of the variable qualitative.
        required: true
        enum: [RISK_FACTOR,BLOCK]
        (annotations.enumDescription):
        - RISK_FACTOR: "Variables related to a risk assestment factor."
        - BLOCK: "Block of qualitative variables related to a figure assembly."

    