#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  interestCoverageWithEbitda:
    type: object
    description: "Interest coverage with EBITDA ratio."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

