#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  averageInventoryTurnover:
    type: object
    description: "It measures the average amount of days it takes the inventory to be sold and replaced in a business."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

