#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  sales:
    type: object
    description: "Change of scale of the sales."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

