#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  group:
    type: object
    description: "Group of classes of economic activities."
    properties:
      id:
        type: string
        description: |
          Identifier of group of classes of economic activities.
        required: true

