#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  netPayBack:
    type: object
    description: "The payback represents the time in years required to earn back the amount invested in an asset from its net cash flows (Years)."
    properties:
      percentage:
        type: number
        description: |
          Percentage of the asset.
        required: true

