#%RAML 1.0 Library
uses:
  annotations: ../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  purpose:
    type: object
    description: "Credit destiny information."
    properties:
      id:
        type: string
        description: |
          Identifier credit destination.
        required: true

      name:
        type: string
        description: |
          Description credit destination.
        required: false

