#%RAML 1.0 Library
uses:
  annotations: ../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  bank: data.riskAnalystAgent.bank.raml
  position: data.riskAnalystAgent.position.raml

types:
  riskAnalystAgent:
    type: object
    description: "Data of the risk analyst in charge of evaluating the proposal data first."
    properties:
      user:
        type: string
        description: |
          User responsible for analyze the proposal.
        required: true

      name:
        type: string
        description: |
          Name of the responsible for analyzing. Responsable to do the sanction.
        required: true

      bank:
        type: bank.bank
        description: |
          Bank where the proposal information is registered
        required: false

      position:
        type: position.position
        description: |
          Information position of the responsible for analyzing. Responsable to do the sanction.
        required: true

