#%RAML 1.0 Library
uses:
  annotations: ../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  code:
    type: object
    description: "Information of the code that describes the type of form issued."
    properties:
      id:
        type: string
        description: |
          Unique code of form.
        required: true

      name:
        type: string
        description: |
          Description of the form type.
        required: false

