#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  imports:
    type: object
    description: "Value corresponding to the financial year."
    properties:
      currency:
        type: string
        description: |
          Type of currency
        required: true

      totalValue:
        type: number
        description: |
          Value corresponding to the financial year.
        required: true

    