#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  shortTerm: data.externalFinancialInformation.balance.shortTerm.raml
  longTerm: data.externalFinancialInformation.balance.longTerm.raml
  debtTotalPrincipal: data.externalFinancialInformation.balance.debtTotalPrincipal.raml
  guarantorTotalAmount: data.externalFinancialInformation.balance.guarantorTotalAmount.raml
  arrearPrincipalAmount: data.externalFinancialInformation.balance.arrearPrincipalAmount.raml

types:
  balance:
    type: object
    description: "Long and short term balance information."
    properties:
      shortTerm:
        type: shortTerm.shortTerm
        description: |
          is the sum of the balances of the financial obligations reported in credit bureaus, with a term shorter or equal to 12 months..
        required: true

      longTerm:
        type: longTerm.longTerm
        description: |
          is the sum of the balances of the financial obligations reported in credit bureaus, with a term greater than 12 months.
        required: true

      debtTotalPrincipal:
        type: debtTotalPrincipal.debtTotalPrincipal
        description: |
          Amount information of the principal value.
        required: false

      guarantorTotalAmount:
        type: guarantorTotalAmount.guarantorTotalAmount
        description: |
          Amount information of the debt as guarantor role.
        required: false

      arrearPrincipalAmount:
        type: arrearPrincipalAmount.arrearPrincipalAmount
        description: |
          Amount information of the non-payment value of the principal debt.
        required: false

