#%RAML 1.0 Library
uses:
  annotations: ../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  linesType:
    type: object
    description: "Relationship between the line and guarantee."
    properties:
      id:
        type: string
        description: |
          Line identifier.
        required: true

    