#%RAML 1.0 Library
uses:
  annotations: ../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  economicGroups:
    type: object
    description: "Information about the economic group in wich is sanctioning the proposal."
    properties:
      id:
        type: string
        description: |
          Economic group's identification.
        required: true

    