#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  value: body.root.business.imports.value.raml

types:
  imports:
    type: object
    description: "Is the value that the client registers before the Dian for each of these items in a determined period comprised of 12 months."
    properties:
      value:
        type: value.value
        description: |
          Imports value.
        required: true

