#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  root: body.root.raml

types:
  body:
    type: object
    description: ""
    properties:
      root:
        type: root.root[]
        description: |
          
        required: true

