#%RAML 1.0 Library
uses:
  annotations: ../../../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  customersLimitAmount: data.details.detailsElements.delegationInput.proposal.customersLimitAmount.raml
  groupLimitAmount: data.details.detailsElements.delegationInput.proposal.groupLimitAmount.raml
  othersLimitAmount: data.details.detailsElements.delegationInput.proposal.othersLimitAmount.raml
  sanction: data.details.detailsElements.delegationInput.proposal.sanction.raml

types:
  proposal:
    type: object
    description: "Information about the risk proposal which is going to be analyzed."
    properties:
      customersLimitAmount:
        type: customersLimitAmount.customersLimitAmount
        description: |
          Monetary amount of the customers limit that can be evaluated on the profile retrieved.
        required: false

      groupLimitAmount:
        type: groupLimitAmount.groupLimitAmount
        description: |
          Monetary amount of the groups limit that can be evaluated on the profile retrieved.
        required: false

      othersLimitAmount:
        type: othersLimitAmount.othersLimitAmount
        description: |
          Monetary amount of others limits that can be evaluated on the profile retrieved.
        required: false

      sanction:
        type: sanction.sanction
        description: |
          Risk sanction information.
        required: true

