#%RAML 1.0 Library
uses:
  annotations: ../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  requestImport:
    type: object
    description: "It is the total value of the item that is being acquired, this value differs from the value that is being requested from the bank."
    properties:
      amount:
        type: number
        description: |
          Requested value for the mortgage loan.
        required: true

      currency:
        type: string
        description: |
          String based on ISO-4217 for specifying the currency related to the amount.
        required: true

