#%RAML 1.0 Library
uses:
  annotations: ../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  commercialChannel: body.commercialChannel.raml
  informationSources: body.informationSources.raml
  participants: body.participants.raml
  products: body.products.raml

types:
  body:
    type: object
    description: ""
    properties:
      commercialChannel:
        type: commercialChannel.commercialChannel
        description: |
          Channel through which scoring is requested.
        required: false

      requestSource:
        type: string
        description: |
          Source from which the request comes (social networks, events).
        required: false

      informationSources:
        type: informationSources.informationSources[]
        description: |
          Contains the source of information with which the information is enriched. This can be SOI / APL, Income Predictor or HDC.
        required: false

      participants:
        type: participants.participants[]
        description: |
          It is the participants to which a credit evaluation is applied.
        required: true

      products:
        type: products.products[]
        description: |
          Detailed information according to the product type.
        required: true

      isIncomeConsolidation:
        type: boolean
        description: |
          Determines if the user's income is consolidated.
        required: false

      isChallenger:
        type: boolean
        description: |
          Determine the policy strategy for user validation.
        required: false

