#%RAML 1.0 Library
uses:
  annotations: ../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  type: body.participants.economicData.incomes.type.raml
  value: body.participants.economicData.incomes.value.raml

types:
  incomes:
    type: object
    description: "Report participant incomes."
    properties:
      type:
        type: type.type
        description: |
          Participant's income type.
        required: true

      value:
        type: value.value
        description: |
          Contains the value associated with the type of income.
        required: false

    