#%RAML 1.0 Library
uses:
  annotations: ../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  purpose:
    type: object
    description: "Purchase destination."
    properties:
      id:
        type: string
        description: |
          Purchase destination identifier.
        required: true

