#%RAML 1.0 Library
uses:
  annotations: ../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  debtAmount:
    type: object
    description: "Debt amount that the person has with the financial system."
    properties:
      amount:
        type: number
        description: |
          Monetary amount.
        required: true

      currency:
        type: string
        description: |
          String based on ISO-4217 for specifying the currency of the amount.
        required: true

