#%RAML 1.0 Library
uses:
  annotations: ../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  value:
    type: object
    description: "Contains the value associated with the deduction type."
    properties:
      amount:
        type: number
        description: |
          Value associated with the deduction type of the participant.
        required: true

      currency:
        type: string
        description: |
          String based on ISO-4217 for specifying the currency related to the amount.
        required: true

