#%RAML 1.0 Library
uses:
  annotations: ../../../../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  declaredVariableIncome:
    type: object
    description: "Variable income declared by the customer."
    properties:
      amount:
        type: number
        description: |
          Variable income amount.
        required: true

      currency:
        type: string
        description: |
          String based on ISO-4217 for specifying the currency of the variable income amount.
        required: true

